#ifndef EXPERIMENTAL_CONSTANTS_H
#define EXPERIMENTAL_CONSTANTS_H

const double SIX_METER_PULSE_HEIGHT_THRESHOLD = 350;
const double FOUR_METER_PULSE_HEIGHT_THRESHOLD = 350;

const double SIX_METER_PSD_THRESHOLD = 1300;
const double FOUR_METER_PSD_THRESHOLD = 1500;

#endif /* EXPERIMENTAL_CONSTANTS_H */
